### ISSUE TITLE
Todo for 0.01

### ISSUE THREAD

**Issue by TotomInc** [TotomInc/universe-god#1]
Once everything on this issue is done, we can merge master to gh-pages.

- [x] tutorial : introduce all gameplay elements, step by step.
- [x] gameplay : earn all basic elements manually or with automation (income/sec).
- [x] gameplay : add upgrades.
- [x] qof : offline production.
- [x] gameplay : add achievements.
- [x] core : add save/load/reset.
- [x] core : add export/import save.

**Comment by TotomInc** [comment]
Tutorial is done.

**Comment by TotomInc** [comment]
Upgrades are implemented.

**Comment by TotomInc** [comment]
Builds implemented.

**Comment by TotomInc** [comment]
Achievements implemented.

**Comment by TotomInc** [comment]
Save system finished, offline production is working. Need to work on export/import.

**Comment by TotomInc** [comment]
Export/import added, game ready to 0.01.
